# 450+ Practice Questions From Pandas, NumPy, and SQL.

Author: Avi Chawla

LinkedIn: https://www.linkedin.com/in/avi-chawla/

Read my blogs here: https://medium.com/@avi_chawla

## Introduction

This notebook has been created for you to practice three of the most common tools used in building any machine learning or data science applications, i.e., Pandas, NumPy, and SQL!

The practice questions provided will serve as a great resource for those who are looking to familiarize themselves with some of the most common functions used in these tools. 

Appropriate descriptions have been provided for all the questions in this entire exercise which will help you navigate through this exercise easily. If a dataset is to be loaded in the python environment, that has also been provided for you. You can find it on the right panel in the Files section. Do NOT delete any of the files/folders listed there. 

The whole exercise has been divided into nine separate notebooks. Below are the links to all the other notebooks for you to jump from one notebook to another:

- **Pandas**

1. Pandas Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-1-d693ac55-6455-40cf-ae34-867c6a02014e/notebook/6449493c84734151b11f4b6871f045d2#99f75bf946d04b9bb1daa9e14c2cfea9) 
2. Pandas Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-employee-dataset-7e3b6755-5d4b-464b-9b75-9c84667ae3bd/notebook/notebook-0de50f3b70834570b13b651dde44c491) 

3. Pandas Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-employee-part-2-adc5a3ee-5f61-4725-8e46-ccb07899acfc/notebook/notebook-78e3faf901da4f14881ef24e41c80bf6) 

4. Pandas Notebook 4: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-after-employee-f84e02a1-fb6a-428e-af90-8dd99855749a/notebook/notebook-134ac20c38ef45e5a4432abd638e6c2e) 

- **NumPy**

1. NumPy Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Numpy-part-1-9b9979f2-b708-4292-b466-3d0157564c91/notebook/notebook-07232b5ebafe49b198a9c55c553414f1) 

2. NumPy Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-2-4456411e-2ddd-426d-8027-4881080027db/notebook/notebook-988aba30f33a45a3861adc4f6a6f338c) **(This Notebook)** 

3. NumPy Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-3-e6587114-b580-4249-b599-540de859e603/notebook/notebook-bb52759ea3f542eaaed9958b5df9c34b)

- **SQL**

1. SQL Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-1-eac9d782-a9b1-4e84-a1f9-af14080a6121/notebook/notebook-697f04297c664d02901db0f85431512e)

2. SQL Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-2-1914b214-be03-44a1-be63-ad99e98be639/notebook/notebook-e549236b988c42a5b53126a7ebb98127)

## How to use this notebook?

At the top right corner, you will find a Duplicate button. This will allow you to create a unique notebook for your own practice and write solutions to the question listed in this notebook.  

If you face any issues or have any feedback, feel free to reach out to me (Avi Chawla) either on Linkedin: https://www.linkedin.com/in/avi-chawla/ or write an email to avi@dsscholar[dot]com. 

Let's begin 🚀!

# NumPy Notebook 2

## Mathematical Operations on NumPy Arrays

In [1]:
import numpy as np
import pandas as pd

### 36. Add two numpy arrays element-wise

In [ ]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.add(a,b) #a+b works too
print(np_array)

[[2 3 6]
 [2 3 6]
 [3 4 8]]


### 37. Multiple two numpy arrays element-wise

In [4]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.multiply(a,b)
print(np_array)

[[ 1  2  9]
 [ 1  2  9]
 [ 2  3 16]]


### 38. Subtract two numpy arrays element-wise

In [5]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = a-b
print(np_array)

[[ 0 -1  0]
 [ 0 -1  0]
 [-1 -2  0]]


### 39. Divide two numpy arrays element-wise

In [6]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = np.divide(a,b)
print(np_array)

[[1.         0.5        1.        ]
 [1.         0.5        1.        ]
 [0.5        0.33333333 1.        ]]


### 40-42. Trigonometric functions

### sin(x)

In [7]:
a = np.array([1,2,3])

np_array = np.sin(a)
print(np_array)

[0.84147098 0.90929743 0.14112001]


### cos(x)

In [8]:
a = np.array([1,2,3])

np_array = np.cos(a)
print(np_array)

[ 0.54030231 -0.41614684 -0.9899925 ]


### tan(x)

In [9]:
a = np.array([1,2,3])

np_array = np.tan(a)
print(np_array)

[ 1.55740772 -2.18503986 -0.14254654]


### 43. Print the element-wise floor 

In [10]:
a = np.linspace(1, 2, 5)

np_array = np.floor(a)
print(np_array)

[1. 1. 1. 1. 2.]


### 44. Print the element-wise ceil

In [11]:
a = np.linspace(1, 2, 5)

np_array = np.ceil(a)
print(np_array)

[1. 2. 2. 2. 2.]


### 45. Print the element-wise nearest integer

In [14]:
a = np.linspace(1, 2, 5)

np_array = np.rint(a)
print(np_array)

[1. 1. 2. 2. 2.]


### 46. Round to given number of decimal places

In [13]:
a = np.linspace(1, 2, 7)
decimal_places = 2

np_array = np.round(a)
print(np_array)

[1. 1. 1. 2. 2. 2. 2.]


### 47. Calculate the element-wise exponential

In [16]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.exp(a)
print(np_array)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### 48. Calculate the element-wise exponential and round to two decimal places

In [17]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.round(np.exp(a),2)
print(np_array)

[  2.72   7.39  20.09  54.6  148.41]


### 49. Calculate the element-wise natural logarithm 

In [18]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.log(a)
print(np_array)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


### 50. Calculate the element-wise natural logarithm and round to two decimal places

In [19]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.round(np.log(a),2)
print(np_array)

[0.   0.69 1.1  1.39 1.61]


### 51. Calculate the element-wise logarithm at base 2

In [20]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])


np_array = np.log2(a)
print(np_array)

[0.         1.         1.5849625  2.         2.32192809]


### 52. Calculate the element-wise logarithm at base 2 and take floor of the result

In [21]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = np.floor(np.log2(a))
print(np_array)

[0. 1. 1. 2. 2.]


### 53. Find the sum of numpy array elements

In [22]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a)
print(sum_of_array)

10


### 54. Find the row-wise sum of numpy array elements

In [27]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a,axis=1)
print(sum_of_array)

[3 7]


### 55. Find the column-wise sum of numpy array elements

In [28]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = np.sum(a,axis=0)
print(sum_of_array)

[4 6]


### 56. Calculate the product of array elements

In [29]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a)
print(prod_of_array)

24


### 57. Find the row-wise product of numpy array elements

In [31]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a,axis=1)
print(prod_of_array)

[ 2 12]


### 58. Find the column-wise product of numpy array element

In [33]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = np.prod(a,axis=0)
print(prod_of_array)

[3 8]


### 59. Compute the square root of array elements

In [34]:
a = np.array([[1, 2], [3, 4]])

np_array = np.sqrt(a)
print(np_array)

[[1.         1.41421356]
 [1.73205081 2.        ]]


## Matrix and Vector Operations

### 60. Compute the dot product of two NumPy arrays 

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.vdot(a,b)
print(np_array)

10


### 61. Compute the row-wise dot product of two NumPy arrays 

In [38]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.dot(a,b)
print(np_array)

[[3 3]
 [7 7]]


### 62. Compute the matrix product of two NumPy arrays

In [40]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = np.matmul(a,b)
print(np_array)

[[3 3]
 [7 7]]


### 63. Compute the matrix product of two NumPy arrays using the @ operator

In [42]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = a@b
print(np_array)

[[3 3]
 [7 7]]


### 64. Compute the length of the vector

In [43]:
a = np.arange(-4, 5)

vec_len = len(a)
print(vec_len)

9


### 65. Sort the array inplace row-wise

In [44]:
a = np.array([[1,4],[3,1]])

np_array = np.sort(a)
print(np_array)

[[1 4]
 [1 3]]


### 66. Sort the array inplace column-wise

In [46]:
a = np.array([[1,4],[3,1]])

np_array = np.sort(a,axis=0)
print(np_array)

[[1 1]
 [3 4]]


### 67. Sort the flattened array

In [47]:
a = np.array([[1,4],[3,1]])

np_array =np.sort(a.flatten())
print(np_array)

[1 1 3 4]


### 68. Order of Indices in a Sorted NumPy Array

In [50]:
a = np.array([3, 1, 2])

np_array = np.argsort(a,axis=0)
print(np_array)

[1 2 0]


### 69-71. Find the index corresponding to the Maximum Values.

In [51]:
a = np.array([[15, 13, 10,  1, 18],
              [14, 19, 19, 17,  8]])

### -> In a flattened array

In [53]:
max_index = np.argmax(a.flatten())
print(max_index)
a.flatten()

6


array([15, 13, 10,  1, 18, 14, 19, 19, 17,  8])

### -> Indices of max along column

In [54]:
max_index = np.argmax(a,axis=0)
print(max_index)

[0 1 1 1 0]


### -> Indices of max along row

In [55]:
max_index = np.argmax(a,axis=1)
print(max_index)

[4 1]


### 72-74. Find the index corresponding to the Minimum Values.

In [56]:
a = np.array([[15, 13, 10,  1, 18],
              [14, 19, 19, 17,  8]])

### -> In a flattened array

In [57]:
min_index = np.argmin(a.flatten())
print(min_index)

3


### -> Indices of min along column

In [58]:
min_index =np.argmin(a,axis=0)
print(min_index)

[1 0 0 0 1]


### -> Indices of min along row

In [60]:
min_index = np.argmin(a,axis=1)
print(min_index)

[3 4]


### 75. Print the indices of non-zero elements

In [65]:
a = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])

non_zero_ind,z = np.nonzero(a)
print(non_zero_ind)
z

[0 1 2 2]


array([0, 1, 0, 1], dtype=int64)

### 76. Find the mean of the whole numpy array

In [66]:
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a)
print(mean)

2.5


### 77. Find the mean of the numpy array along row-axis

In [67]:
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a,axis=1)
print(mean)

[1.5 3.5]


### 78. Find the mean of the numpy array along column-axis

In [68]:
a = np.array([[1, 2], [3, 4]])

mean = np.mean(a,axis=0)
print(mean)

[2. 3.]


### 79. Find the median of the whole numpy array

In [70]:
a = np.array([[1, 2], [3, 4]])

median = np.median(a)
print(median)

2.5


### 80. Find the median of the numpy array along row-axis

In [71]:
a = np.array([[1, 2], [3, 4]])

median = np.median(a,axis=1)
print(median)

[1.5 3.5]


### 81. Find the median of the numpy array along column-axis

In [72]:
a = np.array([[1, 2], [3, 4]])

median = np.median(a,axis=0)
print(median)

[2. 3.]


### 82. Find the std dev of the whole numpy array

In [73]:
a = np.array([[1, 2], [3, 4]])

std_dev = np.std(a)
print(std_dev)

1.118033988749895


### 83. Find the std dev of the numpy array along row-axis

In [74]:
a = np.array([[1, 2], [3, 4]])

std_dev = np.std(a,axis=1)
print(std_dev)

[0.5 0.5]


### 84. Find the std dev of the numpy array along column-axis

In [75]:
a = np.array([[1, 2], [3, 4]])

std_dev = np.std(a,axis=0)
print(std_dev)

[1. 1.]


Great job solving this notebook. Go to NumPy Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-3-e6587114-b580-4249-b599-540de859e603/%2Fnotebook.ipynb)