# 450+ Practice Questions From Pandas, NumPy, and SQL.

Author: Avi Chawla

LinkedIn: https://www.linkedin.com/in/avi-chawla/

Read my blogs here: https://medium.com/@avi_chawla

## Introduction

This notebook has been created for you to practice three of the most common tools used in building any machine learning or data science applications, i.e., Pandas, NumPy, and SQL!

The practice questions provided will serve as a great resource for those who are looking to familiarize themselves with some of the most common functions used in these tools. 

Appropriate descriptions have been provided for all the questions in this entire exercise which will help you navigate through this exercise easily. If a dataset is to be loaded in the python environment, that has also been provided for you. You can find it on the right panel in the Files section. Do NOT delete any of the files/folders listed there. 

The whole exercise has been divided into nine separate notebooks. Below are the links to all the other notebooks for you to jump from one notebook to another:

- **Pandas**

1. Pandas Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-1-d693ac55-6455-40cf-ae34-867c6a02014e/notebook/6449493c84734151b11f4b6871f045d2#99f75bf946d04b9bb1daa9e14c2cfea9) 
2. Pandas Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-employee-dataset-7e3b6755-5d4b-464b-9b75-9c84667ae3bd/notebook/notebook-0de50f3b70834570b13b651dde44c491) 

3. Pandas Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-employee-part-2-adc5a3ee-5f61-4725-8e46-ccb07899acfc/notebook/notebook-78e3faf901da4f14881ef24e41c80bf6) 

4. Pandas Notebook 4: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-after-employee-f84e02a1-fb6a-428e-af90-8dd99855749a/notebook/notebook-134ac20c38ef45e5a4432abd638e6c2e) 

- **NumPy**

1. NumPy Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Numpy-part-1-9b9979f2-b708-4292-b466-3d0157564c91/notebook/notebook-07232b5ebafe49b198a9c55c553414f1) 

2. NumPy Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-2-4456411e-2ddd-426d-8027-4881080027db/notebook/notebook-988aba30f33a45a3861adc4f6a6f338c)  

3. NumPy Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-3-e6587114-b580-4249-b599-540de859e603/notebook/notebook-bb52759ea3f542eaaed9958b5df9c34b) **(This Notebook)**

- **SQL**

1. SQL Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-1-eac9d782-a9b1-4e84-a1f9-af14080a6121/notebook/notebook-697f04297c664d02901db0f85431512e)

2. SQL Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-2-1914b214-be03-44a1-be63-ad99e98be639/notebook/notebook-e549236b988c42a5b53126a7ebb98127)

## How to use this notebook?

At the top right corner, you will find a Duplicate button. This will allow you to create a unique notebook for your own practice and write solutions to the question listed in this notebook.  

If you face any issues or have any feedback, feel free to reach out to me (Avi Chawla) either on Linkedin: https://www.linkedin.com/in/avi-chawla/ or write an email to avi@dsscholar[dot]com. 

Let's begin 🚀!

# NumPy Notebook 3

In [1]:
import numpy as np
import pandas as pd

### 85. Print the data type of the numpy array below 

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

data_type = a.dtype
print(data_type)

int32


### 86. Print the second element in the first row

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

element = a[0][1]
print(element)

2


### 87. Print the first column

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

column = a[:,1]
print(column)

[2 5]


### 88. Print the real part of the NumPy array

In [6]:
a = np.array([1+2j, 2+5j, 4+9j])

real = a.real
print(real)

[1. 2. 4.]


### 89. Print the imaginary part of the NumPy array

In [7]:
a = np.array([1+2j, 2+5j, 4+9j])

img = a.imag
print(img)

[2. 5. 9.]


### 90. Convert the data type from int to float

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

np_array = a.astype(float)
print(np_array)

[[1. 2. 3.]
 [4. 5. 6.]]


### 91. Create a copy of the NumPy array

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])

np_array = np.copy(a)
print(np_array)

[[1 2 3]
 [4 5 6]]


### 92. Print the diagonal of the NumPy array

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])

diag = a.diagonal()
print(diag)

[1 5]


### 93. Change the value of third element in 2nd row to 10

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a[1][2] = 10
print(a)

[[ 1  2  3]
 [ 4  5 10]]


### 94. Create a numpy array of ones with the same shape as the array 'a'. 

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])

np_array = np.ones(a.shape)
print(np_array)

[[1. 1. 1.]
 [1. 1. 1.]]


### 95. Create a numpy array of zeros with the same shape as the array 'a'. 

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])

np_array = np.zeros(a.shape)
print(np_array)

[[0. 0. 0.]
 [0. 0. 0.]]


### 96. Print the sum of the diagonal elements.

The sum of diagonal elements is also called its trace. 

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])

trace = np.sum(np.diagonal(a))
print(trace)

6


### 97. Check whether all the elements of the array are finite or not 

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])

check_finite = np.isfinite(a)
print(check_finite)

[[ True  True  True]
 [ True  True  True]]


### 98. Check whether all the elements of the array are finite or not 

In [19]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

check_finite = np.isfinite(a)
print(check_finite)

[[ True  True  True]
 [ True  True False]]


### 99. Check whether the two numpy arrays are equal or not. 

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]])

check_equal= np.equal(a,b)
print(check_equal)

[[ True  True  True]
 [ True  True  True]]


### 100. Check whether the two numpy arrays are equal or not. 

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]], np.float32)

check_equal= np.equal(a,b)
print(check_equal)

[[ True  True  True]
 [ True  True  True]]


### 101. Sum of array elements

In [24]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_sum = np.sum(a)
print(array_sum)

nan


### 102. Find the sum ignoring the nan elements

In [25]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_sum = np.nansum(a)
print(array_sum)

15.0


### 103. Find the product ignoring the nan elements

In [26]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_prod = np.nanprod(a)
print(array_prod)

120.0


### 104. Find the element-wise absolute value

In [ ]:
a = np.array([[1, -2, 3], [4, -5, 6]])

np_array = np.absolute(a) # same as np.abs()
print(np_array)

[[1 2 3]
 [4 5 6]]


### 105. Count the number of non-zero elements

In [29]:
a = np.array([[0, -2, 3], [4, -5, 6]])

count_non_zero = np.count_nonzero(a)
print(count_non_zero)

5


### 106. Count the number of non-zero elements row-wise

In [30]:
a = np.array([[0, -2, 3], [4, -5, 6]])

count_non_zero = np.count_nonzero(a,axis=1)
print(count_non_zero)

[2 3]


### 106. Count the number of non-zero elements column-wise

In [31]:
a = np.array([[0, -2, 3], [4, -5, 6]])

count_non_zero = np.count_nonzero(a,axis=0)
print(count_non_zero)

[1 2 2]


### 107. Find the mean ignoring the nan elements

In [32]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_mean = np.nanmean(a)
print(array_mean)

3.0


### 108. Find the std dev ignoring the nan elements

In [33]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_std = np.nanstd(a)
print(array_std)

1.4142135623730951


### 109. Find the median ignoring the nan elements

In [34]:
a = np.array([[1, 2, 3], [4, 5, np.nan]])

array_median = np.nanmedian(a)
print(array_median)

3.0


### 110. Clip the array elements to a range

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])

min_range, max_range = (2, 5)
np_array = np.clip(a,min_range,max_range)
print(np_array)

[[2 2 3]
 [4 5 5]]


### 111-130. As an exercise, frame 20 numpy questions on your own and solve them.

Great job solving this notebook. Go to SQL Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-1-eac9d782-a9b1-4e84-a1f9-af14080a6121/%2Fnotebook.ipynb)